{
 "title": "Cassandra Health - Operator Clusters",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_gc_collection_seconds_sum{cassandra_cluster=~\".+\"}, namespace)"
   },
   {
    "name": "cluster",
    "query": "label_values(jvm_gc_collection_seconds_sum{namespace=\"$namespace\"}, cassandra_cluster)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
   }
  ]
 },
 "panels": [
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$namespace\", persistentvolumeclaim=~\".+$cluster.+\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Cassandra up/down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{cassandra_cluster=\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cassandra process RSS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "% of a core" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod_name)(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name=\"cassandra\",pod_name=~\"$pod\"} - container_cpu_usage_seconds_total{namespace=~\"$namespace\",container_name=\"cassandra\",pod_name=~\"$pod\"} offset 30s)) / 30",
     "legendFormat": "{{ pod_name }} CPU Total"
    },
    {
     "expr": "(sum by (pod_name)(container_cpu_user_seconds_total{namespace=~\"$namespace\",container_name=\"cassandra\",pod_name=~\"$pod\"} - container_cpu_user_seconds_total{namespace=~\"$namespace\",container_name=\"cassandra\",pod_name=~\"$pod\"} offset 30s)) / 30",
     "legendFormat": "{{ pod_name }} CPU User"
    },
    {
     "expr": "(sum by (pod_name)(container_cpu_system_seconds_total{namespace=~\"$namespace\",container_name=\"cassandra\",pod_name=~\"$pod\"} - container_cpu_system_seconds_total{namespace=~\"$namespace\",container_name=\"cassandra\",pod_name=~\"$pod\"} offset 30s)) / 30",
     "legendFormat": "{{ pod_name }} CPU System"
    }
   ]
  },
  { "title": "Read/Write throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Write count per coordinator [rate-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "requests / second" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_write_latency_count{namespace=\"$namespace\", cassandra_cluster=\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read count per coordinator [rate-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "requests / second" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_read_latency_count{namespace=\"$namespace\", cassandra_cluster=\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Read/Write Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Write latency coordinator + replicas  - 99th",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "µs", "label": "time per request" }
   ],
   "targets": [
    {
     "expr": "cassandra_clientrequest_write_latency_99thpercentile{namespace=\"$namespace\", cassandra_cluster=\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} 99th"
    }
   ]
  },
  {
   "title": "Read latency coordinator + replicas - 99th",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "µs", "label": "time per request" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (cassandra_clientrequest_read_latency_99thpercentile{namespace=\"$namespace\", cassandra_cluster=\"$cluster\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} 99th"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "JVM heap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", pool=~\".*Eden.*\", namespace=\"$namespace\", pod=~\"$pod\"} + on(pod) jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", pool=~\".*Survivor.*\", namespace=\"$namespace\", pod=~\"$pod\"} + on(pod) jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", pool=~\".*Gen.*\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "JVM non-heap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", pool=~\".*Code.*\", namespace=\"$namespace\", pod=~\"$pod\"} + on(pod) jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", pool=~\".*Meta.*\", namespace=\"$namespace\", pod=~\"$pod\"} + on(pod) jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", pool=~\".*Compress.*\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Blocked tasks count [increase-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_tps_totalblockedtasks_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} {{pool_name}}"
    }
   ]
  },
  {
   "title": "Pending tasks count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, pool_name) (cassandra_tps_pendingtasks{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} {{pool_name}}"
    }
   ]
  },
  {
   "title": "Unavailable read/write requests count [increase-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_clientrequest_read_unavailables_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m]) + increase(cassandra_clientrequest_write_unavailables_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} reads"
    },
    {
     "expr": "increase(cassandra_clientrequest_write_unavailables_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m]) + increase(cassandra_clientrequest_write_unavailables_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} writes"
    }
   ]
  },
  {
   "title": "Timeout read/write requests count [increase-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_clientrequest_read_timeouts_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m]) + increase(cassandra_clientrequest_write_timeouts_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} reads"
    },
    {
     "expr": "increase(cassandra_clientrequest_write_timeouts_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m]) + increase(cassandra_clientrequest_write_timeouts_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} writes"
    }
   ]
  },
  {
   "title": "Node-to-Node connection timeout [increase-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_connection_timeouts_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} -> {{address}}"
    }
   ]
  },
  {
   "title": "Dropped messages count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cassandra_droppedmessage_dropped_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])) by (pod, message_type) ",
     "legendFormat": "{{pod}} {{message_type}}"
    }
   ]
  }
 ]
}
{
 "title": "Cassandra Compactions - Operator Clusters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_memory_pool_bytes_used{cassandra_cluster=~\".+\"},namespace)"
   },
   {
    "name": "cluster",
    "query": "label_values(jvm_memory_pool_bytes_used{namespace=\"$namespace\"}, cassandra_cluster)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_memory_pool_bytes_used{cassandra_cluster=\"$cluster\", namespace=\"$namespace\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pending compactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_all_pendingcompactions{cassandra_cluster=\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pending Tasks In Compaction TP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_tps_pendingtasks{cassandra_cluster=\"$cluster\",pool_name=\"CompactionExecutor\", pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "# of SSTables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_table_livesstablecount{cassandra_cluster=\"$cluster\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Write IIOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_total{namespace=\"$namespace\", device=\"\", pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod_name=~\"$pod\", device=\"\"}[1m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "(Memtable heap size) - we use off-heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_all_allmemtablesheapsize{namespace=\"$namespace\", cassandra_cluster=\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memtable live data size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_all_allmemtableslivedatasize{namespace=\"$namespace\", cassandra_cluster=\"$cluster\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tombstones scanned per query 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_all_tombstonescannedhistogram_99thpercentile{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} p99"
    }
   ]
  },
  {
   "title": "Live cells scanned per query 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_table_all_livescannedhistogram_99thpercentile{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Cassandra Keyspace Stats - Operator Clusters",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_memory_pool_bytes_used{cassandra_cluster=~\".+\"},namespace)"
   },
   {
    "name": "cluster",
    "query": "label_values(jvm_memory_pool_bytes_used{namespace=\"$namespace\"}, cassandra_cluster)"
   },
   {
    "name": "keyspace",
    "query": "label_values(cassandra_table_livediskspaceused{cassandra_cluster=\"$cluster\",namespace=\"$namespace\"},keyspace)"
   },
   {
    "name": "table",
    "query": "label_values(cassandra_table_livediskspaceused{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", keyspace=\"$keyspace\"}, table)"
   },
   {
    "name": "pod",
    "query": "label_values(cassandra_table_livediskspaceused{cassandra_cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Disk Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average table disk load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cassandra_table_livediskspaceused{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", keyspace=~\"$keyspace\", table=~\"$table\", pod=~\"$pod\"}) by (keyspace, table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  { "title": "Tombstones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "999th tombstones scanned",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_tombstonescannedhistogram_999thpercentile{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", keyspace=~\"$keyspace\", table=~\"$table\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} {{keyspace}} {{table}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Max row size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_table_maxpartitionsize{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", keyspace=~\"$keyspace\", table=~\"$table\", pod=~\"$pod\"}) by (keyspace, table)",
     "legendFormat": "{{keyspace}} {{table}}"
    }
   ]
  },
  { "title": "Table Read/Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Table write count local to node [rate-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_table_writelatency_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", keyspace=~\"$keyspace\", table=~\"$table\", pod=~\"$pod\"}[1m])) by (keyspace, table)",
     "legendFormat": "{{keyspace}} {{table}}"
    },
    {}
   ]
  },
  {
   "title": "Table read count local to node [rate-1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_table_readlatency_count{cassandra_cluster=\"$cluster\", namespace=\"$namespace\", keyspace=~\"$keyspace\", table=~\"$table\", pod=~\"$pod\"}[1m])) by (keyspace, table)",
     "legendFormat": "{{keyspace}} {{table}}"
    }
   ]
  },
  { "title": "Table Read/Write $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "pod" },
  {
   "title": "Table write latency local to node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_writelatency_999thpercentile{cassandra_cluster=\"$cluster\", keyspace=~\"$keyspace\", table=~\"$table\", pod=\"$pod\"}",
     "legendFormat": "{{pod}} {{keyspace}} {{table}} 999th"
    }
   ]
  },
  {
   "title": "Table read latency local to node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_writelatency_999thpercentile{cassandra_cluster=\"$cluster\", keyspace=~\"$keyspace\", table=~\"$table\", pod=\"$pod\"}",
     "legendFormat": "{{pod}} {{keyspace}} {{table}} 999th"
    }
   ]
  }
 ]
}
{
 "title": "Cassandra Memory & GC - Operator Clusters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_gc_collection_seconds_sum{cassandra_cluster=~\".+\"}, namespace)"
   },
   {
    "name": "cluster",
    "query": "label_values(jvm_gc_collection_seconds_sum{namespace=\"$namespace\"}, cassandra_cluster)"
   },
   {
    "name": "pod",
    "query": "label_values(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", cassandra_cluster=\"$cluster\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "GCs [30s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Time Spent (s)" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (jvm_gc_collection_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"})  - sum by (pod) (jvm_gc_collection_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"} offset 30s)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GC ParNew[30s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{gc=\"ParNew\", namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"} - jvm_gc_collection_seconds_sum{gc=\"ParNew\", namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"} offset 30s",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GC CMS[30s]",
   "type": "graph",
   "description": "Includes only STW pauses in CMS",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{gc=\"ConcurrentMarkSweep\", namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"} - jvm_gc_collection_seconds_sum{gc=\"ConcurrentMarkSweep\", namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"} offset 30s",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Average GC time [30s]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"}) by (cassandra_cluster, pod) - sum(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"} offset 30s) by (cassandra_cluster, pod)) / (sum(jvm_gc_collection_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"}) by (cassandra_cluster, pod) - sum(jvm_gc_collection_seconds_count{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\"} offset 30s) by (cassandra_cluster, pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Filesystem Cache",
   "type": "graph",
   "description": "How much of the filesystem (cassandra data files) are cached in memory.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=\"cassandra\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "description": "How much memory is completely free. If this is low, it indicates not enough space for filesystem cache.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=\"cassandra\"} - container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\"$pod\", container_name=\"cassandra\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\", pool=~\".*Eden Space\"}",
     "legendFormat": "{{pod}} Eden"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\",pool=~\".*Survivor Space\"}",
     "legendFormat": "{{pod}} Survivor"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\",pool=~\".*Old Gen\"}",
     "legendFormat": "{{pod}} Old"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\",pool=\"Metaspace\"}",
     "legendFormat": "{{ pod }} Metaspace"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", pod=~\"$pod\", cassandra_cluster=\"$cluster\",pool=\"Code Cache\"}",
     "legendFormat": "{{ pod }} "
    }
   ]
  }
 ]
}