apiVersion: batch/v1
kind: Job
metadata:
  name: policy-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - args: [whoami]
        image: alpine
        imagePullPolicy: Always
        name: policy-test
