# tell kind nodes to proxy TCP requests on port 5000 to the docker host on the same port
# this is so that kind nodes can pull the "local" image from the docker host
# based on https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/56#issuecomment-387463386
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-proxy
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: registry-proxy
  template:
    metadata:
      labels:
        app: registry-proxy
    spec:
      hostNetwork: true
      containers:
        - image: "tecnativa/tcp-proxy"
          name: tcp-proxy
          command: ["/bin/sh", "-c"]
          args:
            - export TALK=$(/sbin/ip route |  awk '/default/ { print $3 ":5000"}');
              export LISTEN=:5000;
              /magic-entrypoint /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg;
          ports:
            - containerPort: 5000
